object frmMsg_Operador: TfrmMsg_Operador
  Left = 438
  Top = 447
  BorderIcons = []
  BorderStyle = bsNone
  Caption = 'Mensagem ao Operador'
  ClientHeight = 102
  ClientWidth = 368
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = [fsBold]
  OldCreateOrder = False
  Position = poDesktopCenter
  OnHide = FormHide
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 368
    Height = 102
    Align = alClient
    BevelOuter = bvNone
    BorderWidth = 2
    Color = 8404992
    ParentBackground = False
    TabOrder = 0
    ExplicitLeft = 56
    ExplicitTop = 32
    ExplicitWidth = 353
    ExplicitHeight = 97
    object Panel2: TPanel
      Left = 2
      Top = 2
      Width = 364
      Height = 98
      Align = alClient
      BevelOuter = bvNone
      BorderWidth = 2
      Color = clWhite
      ParentBackground = False
      TabOrder = 0
      ExplicitLeft = 0
      ExplicitWidth = 349
      ExplicitHeight = 93
      object Panel3: TPanel
        Left = 2
        Top = 2
        Width = 360
        Height = 94
        Align = alClient
        BevelOuter = bvNone
        BorderWidth = 5
        Color = 8404992
        ParentBackground = False
        TabOrder = 0
        ExplicitLeft = 66
        ExplicitWidth = 349
        ExplicitHeight = 93
        object Image2: TImage
          Left = 19
          Top = 22
          Width = 51
          Height = 51
          Center = True
        end
        object lb_msg: TLabel
          Left = 90
          Top = 5
          Width = 265
          Height = 84
          Align = alRight
          Alignment = taCenter
          AutoSize = False
          Caption = 'Aguarde'
          Color = clBtnFace
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -15
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentColor = False
          ParentFont = False
          Transparent = True
          Layout = tlCenter
          WordWrap = True
          ExplicitLeft = 96
          ExplicitTop = 3
          ExplicitHeight = 81
        end
      end
    end
  end
end
